/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/play/GenerateAudioNumbers copy.vue')['default']
    GenerateAudioNumbers: typeof import('./components/play/GenerateAudioNumbers.vue')['default']
    GenerateAudioTime: typeof import('./components/play/GenerateAudioTime.vue')['default']
    PageFooter: typeof import('./components/base/PageFooter.vue')['default']
    PageHeader: typeof import('./components/base/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsModal: typeof import('./components/modals/SettingsModal.vue')['default']
  }
}
